// <auto-generated />
using System;
using HelpDeskAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HelpDeskAPI.Migrations
{
    [DbContext(typeof(HelpDeskContext))]
    [Migration("20260414102729_update4")]
    partial class update4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HelpDeskAPI.Models.Calendrier", b =>
                {
                    b.Property<int>("CalendrierId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CalendrierId"));

                    b.Property<int>("CreateurId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CalendrierId");

                    b.HasIndex("CreateurId");

                    b.HasIndex("TicketId");

                    b.ToTable("Calendriers");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.CalendrierUtilisateur", b =>
                {
                    b.Property<int>("CalendrierId")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("CalendrierId", "UtilisateurId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("CalendrierUtilisateurs");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Client", b =>
                {
                    b.Property<int>("ClientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ClientId"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailContact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fax")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatriculeFiscale")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomSociete")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SiteWeb")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ClientId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Commentaire", b =>
                {
                    b.Property<int>("CommentaireId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentaireId"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<bool>("PublieKnowledgeBase")
                        .HasColumnType("bit");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("CommentaireId");

                    b.HasIndex("TicketId")
                        .IsUnique();

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Commentaires");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Message", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Contenu")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<int>("DestinataireId")
                        .HasColumnType("int");

                    b.Property<bool>("EstLu")
                        .HasColumnType("bit");

                    b.Property<int>("ExpediteurId")
                        .HasColumnType("int");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("MessageId");

                    b.HasIndex("DestinataireId");

                    b.HasIndex("ExpediteurId");

                    b.HasIndex("TicketId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.MicroService", b =>
                {
                    b.Property<int>("MicroServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MicroServiceId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("MicroServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("MicroServices");

                    b.HasData(
                        new
                        {
                            MicroServiceId = 1,
                            Nom = "Power Apps",
                            ServiceId = 1
                        },
                        new
                        {
                            MicroServiceId = 2,
                            Nom = "Power Automate",
                            ServiceId = 1
                        },
                        new
                        {
                            MicroServiceId = 3,
                            Nom = "Power BI",
                            ServiceId = 1
                        },
                        new
                        {
                            MicroServiceId = 4,
                            Nom = "Power Pages",
                            ServiceId = 1
                        },
                        new
                        {
                            MicroServiceId = 5,
                            Nom = "Copilot",
                            ServiceId = 1
                        },
                        new
                        {
                            MicroServiceId = 6,
                            Nom = "SharePoint",
                            ServiceId = 1
                        },
                        new
                        {
                            MicroServiceId = 7,
                            Nom = "Réseaux et sécurité",
                            ServiceId = 2
                        },
                        new
                        {
                            MicroServiceId = 8,
                            Nom = "Gestion serveur",
                            ServiceId = 2
                        },
                        new
                        {
                            MicroServiceId = 9,
                            Nom = "Support et maintenance",
                            ServiceId = 2
                        },
                        new
                        {
                            MicroServiceId = 10,
                            Nom = "Stockage et sauvegarde",
                            ServiceId = 2
                        },
                        new
                        {
                            MicroServiceId = 11,
                            Nom = "Conseil et suivi",
                            ServiceId = 2
                        },
                        new
                        {
                            MicroServiceId = 12,
                            Nom = "Développement web",
                            ServiceId = 3
                        },
                        new
                        {
                            MicroServiceId = 13,
                            Nom = "Développement mobile",
                            ServiceId = 3
                        },
                        new
                        {
                            MicroServiceId = 14,
                            Nom = "Design UI/UX",
                            ServiceId = 3
                        },
                        new
                        {
                            MicroServiceId = 15,
                            Nom = "Conception graphique",
                            ServiceId = 3
                        },
                        new
                        {
                            MicroServiceId = 16,
                            Nom = "Autre (espace libre)",
                            ServiceId = 4
                        });
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime>("DateEnvoi")
                        .HasColumnType("datetime2");

                    b.Property<bool>("EstLue")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.PieceJointe", b =>
                {
                    b.Property<int>("PieceJointeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PieceJointeId"));

                    b.Property<string>("Chemin")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomFichier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("PieceJointeId");

                    b.HasIndex("TicketId");

                    b.ToTable("PiecesJointes");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Nom = "Microsoft"
                        },
                        new
                        {
                            ServiceId = 2,
                            Nom = "HelpDesk"
                        },
                        new
                        {
                            ServiceId = 3,
                            Nom = "Développement"
                        },
                        new
                        {
                            ServiceId = 4,
                            Nom = "Autre"
                        });
                });

            modelBuilder.Entity("HelpDeskAPI.Models.StatistiqueTicket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<double>("Duree")
                        .HasColumnType("float");

                    b.Property<string>("NomAgent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Service")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.ToTable("StatistiquesTickets");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TicketId"));

                    b.Property<int>("CreateurId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateDebut")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFin")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DatePrevueFin")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MicroServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Priorite")
                        .HasColumnType("int");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.Property<double>("TempsTotalHeures")
                        .HasColumnType("float");

                    b.Property<int?>("TicketFusionneAvecId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TravailEffectue")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TicketId");

                    b.HasIndex("CreateurId");

                    b.HasIndex("MicroServiceId");

                    b.HasIndex("ServiceId");

                    b.HasIndex("TicketFusionneAvecId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.TicketAssignation", b =>
                {
                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DateAssignation")
                        .HasColumnType("datetime2");

                    b.HasKey("TicketId", "UtilisateurId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("TicketAssignations");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.TimeSheet", b =>
                {
                    b.Property<int>("TimeSheetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TimeSheetId"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilisateurId")
                        .HasColumnType("int");

                    b.HasKey("TimeSheetId");

                    b.HasIndex("TicketId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("TimeSheets");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Utilisateur", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.HasKey("UserId");

                    b.ToTable("Utilisateurs");

                    b.HasDiscriminator<string>("UserType").HasValue("Utilisateur");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Agent", b =>
                {
                    b.HasBaseType("HelpDeskAPI.Models.Utilisateur");

                    b.Property<int>("MicroServiceId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<int>("Statut")
                        .HasColumnType("int");

                    b.HasIndex("MicroServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Utilisateurs", t =>
                        {
                            t.Property("Statut")
                                .HasColumnName("Agent_Statut");
                        });

                    b.HasDiscriminator().HasValue("Agent");

                    b.HasData(
                        new
                        {
                            UserId = 101,
                            DateCreation = new DateTime(2026, 4, 14, 11, 27, 28, 698, DateTimeKind.Local).AddTicks(5269),
                            Email = "jean.dubois@itanis.com",
                            Nom = "Dubois",
                            PasswordHash = "$2a$11$0GkDCB2zVR2m9PrpLtWLB.20NkOYe09ArWHzMItro6I6JIZa9gomy",
                            Prenom = "Jean",
                            Role = "Agent",
                            MicroServiceId = 1,
                            ServiceId = 1,
                            Statut = 0
                        },
                        new
                        {
                            UserId = 102,
                            DateCreation = new DateTime(2026, 4, 14, 11, 27, 28, 818, DateTimeKind.Local).AddTicks(7993),
                            Email = "sophie.martin@itanis.com",
                            Nom = "Martin",
                            PasswordHash = "$2a$11$5R7OJfFYHm7vkC5FtHR1wOMTz6moLwl9k3HDeUal3.D86k3A0c4g6",
                            Prenom = "Sophie",
                            Role = "Agent",
                            MicroServiceId = 8,
                            ServiceId = 2,
                            Statut = 0
                        });
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Admin", b =>
                {
                    b.HasBaseType("HelpDeskAPI.Models.Utilisateur");

                    b.HasDiscriminator().HasValue("Admin");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Collaborateur", b =>
                {
                    b.HasBaseType("HelpDeskAPI.Models.Utilisateur");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoProfil")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasIndex("ClientId");

                    b.HasDiscriminator().HasValue("Collaborateur");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Calendrier", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.Utilisateur", "Createur")
                        .WithMany()
                        .HasForeignKey("CreateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDeskAPI.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Createur");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.CalendrierUtilisateur", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.Calendrier", "Calendrier")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("CalendrierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDeskAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendrier");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Commentaire", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.Ticket", "Ticket")
                        .WithOne("Commentaire")
                        .HasForeignKey("HelpDeskAPI.Models.Commentaire", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDeskAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Message", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.Utilisateur", "Destinataire")
                        .WithMany()
                        .HasForeignKey("DestinataireId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDeskAPI.Models.Utilisateur", "Expediteur")
                        .WithMany()
                        .HasForeignKey("ExpediteurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDeskAPI.Models.Ticket", "Ticket")
                        .WithMany("Messages")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Destinataire");

                    b.Navigation("Expediteur");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.MicroService", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.Service", "Service")
                        .WithMany("MicroServices")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Notification", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HelpDeskAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.PieceJointe", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.Ticket", "Ticket")
                        .WithMany("PiecesJointes")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.StatistiqueTicket", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Ticket", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.Utilisateur", "Createur")
                        .WithMany()
                        .HasForeignKey("CreateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDeskAPI.Models.MicroService", "MicroService")
                        .WithMany("Tickets")
                        .HasForeignKey("MicroServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDeskAPI.Models.Service", "Service")
                        .WithMany("Tickets")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDeskAPI.Models.Ticket", "TicketFusionneAvec")
                        .WithMany()
                        .HasForeignKey("TicketFusionneAvecId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("Createur");

                    b.Navigation("MicroService");

                    b.Navigation("Service");

                    b.Navigation("TicketFusionneAvec");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.TicketAssignation", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.Ticket", "Ticket")
                        .WithMany("Assignes")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HelpDeskAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.TimeSheet", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.Ticket", "Ticket")
                        .WithMany("TimeSheets")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.HasOne("HelpDeskAPI.Models.Utilisateur", "Utilisateur")
                        .WithMany()
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("Agent", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.MicroService", "MicroService")
                        .WithMany("Agents")
                        .HasForeignKey("MicroServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HelpDeskAPI.Models.Service", "Service")
                        .WithMany("Agents")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MicroService");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Collaborateur", b =>
                {
                    b.HasOne("HelpDeskAPI.Models.Client", "Client")
                        .WithMany("Collaborateurs")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Calendrier", b =>
                {
                    b.Navigation("Utilisateurs");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Client", b =>
                {
                    b.Navigation("Collaborateurs");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.MicroService", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Service", b =>
                {
                    b.Navigation("Agents");

                    b.Navigation("MicroServices");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("HelpDeskAPI.Models.Ticket", b =>
                {
                    b.Navigation("Assignes");

                    b.Navigation("Commentaire");

                    b.Navigation("Messages");

                    b.Navigation("PiecesJointes");

                    b.Navigation("TimeSheets");
                });
#pragma warning restore 612, 618
        }
    }
}
